### ISSUE TITLE
Tried to install dependencies, accidentally deleted operating system

### ISSUE THREAD

**Issue by zachwildd** [opensourceryclub/LSTM-Stock-Predictor#2]
So I was browsing your project hoping to make millions trading options. I cloned your repo and followed the instructions in your readme. Alas, the dependencies were missing. I have pip installed so many times that my hard drive is full and I overwrote my operating system. I wish I would have read the warning at the bottom of the readme first... if only it was at the top. 
ps its spelled "Zach"

**Comment by ghost** [comment]
UR DUMB
